### ISSUE TITLE
更新本地所有（all）命令有问题

### ISSUE THREAD

**Issue by qtzheng** [nefe/vscode-pont#1]
有两个数据源，选择一个数据源点all，会把另一个数据源的数据给改掉。

**Comment by loveholly** [comment]
我也遇到了这个问题，如果是多数据源的话，给其中一个数据源生成代码的时候会把其他数据源的类型声明重置成any

![图片](https://user-images.githubusercontent.com/5133856/56331504-293ca980-61bf-11e9-87cc-56de4ac80e1b.png)

**Comment by jasonHzq** [comment]
可以先暂时删除生成代码，重新生成一下。这个问题我排查一下。
